version: "3.9"
services:
  photo-story:
    image: photo-story:distroless
    container_name: photo-story
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/photo-story/logs
    ports:
      - "9000:9000"
    networks:
      - local

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/config.yml"
      - "--web.external-url=http://localhost:9090"
    networks:
      - local

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
    command:
      - -config.file=/etc/loki/config.yml
    networks:
      - local

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail:/etc/promtail
      - ./logs:/var/app_logs
    command:
      - -config.file=/etc/promtail/config.yml
    networks:
      - local

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    user: "0"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - local

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/secret.config.yml"
      - "--web.external-url=http://localhost:9093"
    networks:
      - local

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - local

networks:
  local:
    driver: bridge
