unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_single_line = true
spaces_within_parenthesized_items = true
max_width = 120
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
imports_granularity = "Crate"
use_small_heuristics = "Default"
