unstable_features = true
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
spaces_within_parenthesized_items = true
max_width = 120
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
use_small_heuristics = "Default"
