[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "frontend"
path = "src/bin/main.rs"

[features]
default = []
ssr = ["dioxus-web/hydrate"]

[dependencies]
dioxus = "0.3"
dioxus-router = "0.3"
dioxus-web = "0.3"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
common = { path = "../common" }
wasm-bindgen = "0.2"
web-sys = "0.3"
lol_alloc = "0.3"

[target.'cfg( not( target_arch = "wasm32" ))'.dependencies]
monitoring = { path = "../monitoring" }
settings = { path = "../settings"}

axum = "0.6"
clap = { version = "4.1", features = ["derive"] }
dioxus-ssr = "0.3"
futures = "0.3"
once_cell = "1.17"
serde_json = "1.0"
serde_with = "2.3"
tower = { version = "0.4", features = ["make"] }
tower-http = { version = "0.4", features = ["fs", "compression-br", "cors"] }
tracing = "0.1"
tracing-log = "0.1"
tokio = { version = "1.26", features = ["full"] }

