cargo-features = ["per-package-target"]

[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Henrique Melícias"]
description = "Frontend using Dioxus."
license = "MIT"
forced-target = "wasm32-unknown-unknown"

[[bin]]
name = "frontend"
path = "src/bin/main.rs"

[features]
default = []
ssr = ["dioxus-web/hydrate"]

[dependencies]
common = { path = "../common" }

thiserror = "1.0"
anyhow = "1.0"
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus" }
gloo = "0.8"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
web-sys = "0.3"
lol_alloc = "0.4"