[build]
target = "./trunk_index.html"
dist = "../../target/static"
release = false
public_url = "/"

[watch]
watch = [
    "./trunk_index.html",
    "./src",
    "../../assets"
]

[[proxy]]
backend = "http://localhost:5555"
rewrite = "/api"

[clean]
dist = "../../target/static"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c",
    "just -f $TRUNK_SOURCE_DIR/justfile generate_tailwind_css ./styles"
]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c",
    "just -f $TRUNK_SOURCE_DIR/justfile post_update_index_html $TRUNK_STAGING_DIR/index.html"
]
