scrape_configs:
  - job_name: "photo-story-backend"
    scrape_interval: 5s
    static_configs:
      - targets: [ "photo-story-backend:9000" ]

  - job_name: "photo-story-frontend"
    scrape_interval: 5s
    static_configs:
      - targets: [ "photo-story-frontend:9001" ]

  - job_name: cadvisor
    static_configs:
      - targets: [ "cadvisor:8080" ]

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9093" ]
