[package]
name = "common"
version = "0.1.0"
edition = "2021"
authors = ["Henrique Melícias"]
description = "Common code between the backend and the frontend"
license = "MIT"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
