[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "backend"
path = "src/bin/main.rs"

[features]
default = ["ssr"]
ssr = ["frontend"]

[dependencies]
frontend = { path = "../frontend", optional = true }
common = { path = "../common" }
monitoring = { path = "../monitoring" }
settings = { path = "../settings" }

color-eyre = "0.6"
smartstring = "1.0"
uuid = "1.2"
tracing = "0.1"
tracing-log = "0.1"
dioxus = { version = "0.3" }
dioxus-ssr = { version = "0.3" }
tokio = { version = "1.24", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
derive-getters = "0.2"
lazy_static = "1.4"
axum = "0.6"
clap = { version = "4.0", features = ["derive"] }
tower = { version = "0.4", features = ["make"] }
tower-http = { version = "0.3.5", features = ["full", "fs", "compression-br"] }
futures = { version = "0.3", features = ["std"], default-features = false }
qstring = "0.7"
