[default]
log_level = "debug"
is_stdout_emitted = true
is_file_emitted = true
files_directory = "./logs"
files_prefix = "backend.dev"

[production]
log_level = "info"
is_stdout_emitted = true
is_file_emitted = true
files_directory = "./logs"
files_prefix = "backend.prod"