[default]
log_level = "debug"
is_stdout_emitted = true
files_emitted = { is_emitted = true, dir = "./logs", files_prefix = "backend.dev" }

[production]
log_level = "info"
is_stdout_emitted = true
files_emitted = { is_emitted = true, dir = "./logs", files_prefix = "backend.dev" }
