[default]
sock_addr_v4 = "127.0.0.1:5555"
proxy_url = "http://127.0.0.1:5555"
static_dir = "./static"
assets_dir = "./assets"

[production]
sock_addr_v4 = "0.0.0.0:9001"
proxy_url = "http://0.0.0.0:9000"
static_dir = "./static"
assets_dir = "./assets"